### ISSUE TITLE
Error with Tempcoding_main

### ISSUE THREAD

**Issue by TheAwesomeAndy** [google/ihmehimmeli#4]
'tempcoding_main' is not recognized as an internal or external command,
operable program or batch file.

**Comment by veluca93** [comment]
Hello. How are you running the command?

**Comment by TheAwesomeAndy** [comment]
Hello, Thank you for replying…this has been causing me much stress trying to get this to run.  I am running it literally word for word as per the build commands provided on the GitHub page on a Windows 10 environment. When I enter the command : tempcoding/tempcoding_main -problem=mnist -n_train=54000 -n_validation=6000 -n_test=10000  -batch_size=32 -clip_derivative=539.69973904211679 -decay_rate=0.18176949150701854 -fire_threshold=1.1673205005788956 -learning_rate=0.0010186407877494507 -learning_rate_pulses=0.09537534860701444 -n_hidden=340 -n_pulses=10 -nonpulse_weight_mean_multiplier=-0.2754188425913906 -penalty_no_spike=48.374830659132556 -pulse_weight_mean_multiplier=7.8391245503824578 -update_all_datapoints=true -use_adam=true -n_epochs=100 -mnist_data_path=C:\Users\alane\ihmehimmeli\data I get the response: 'tempcoding' is not recognized as an internal or external command,operable program or batch file. I have the directory named Tempcoding and I have the file tempcoding_main.vcxproj Have you gotten this to run?  If so, did you do anything different that the suggested build instructions. Thanks again for your reply.Andrew   From: Luca VersariSent: Friday, September 25, 2020 2:36 PMTo: google/ihmehimmeliCc: TheAwesomeAndy; AuthorSubject: Re: [google/ihmehimmeli] Error with Tempcoding_main (#4) Hello. How are you running the command?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by veluca93** [comment]
The instructions we provided are for a Linux environment, we never run the code on Windows. Would it be possible for you to run this on a Linux machine?
I am not very familiar with Windows.

**Comment by TheAwesomeAndy** [comment]
Thank you for the information.  Yes, I will try on Linux and let you know – thank you for contacting me -Andrew From: Luca VersariSent: Friday, October 2, 2020 3:11 PMTo: google/ihmehimmeliCc: TheAwesomeAndy; AuthorSubject: Re: [google/ihmehimmeli] Error with Tempcoding_main (#4) The instructions we provided are for a Linux environment, we never run the code on Windows. Would it be possible for you to run this on a Linux machine?I am not very familiar with Windows.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
