### ISSUE TITLE
cc:240: Error computing Lambert W

### ISSUE THREAD

**Issue by TheAwesomeAndy** [google/ihmehimmeli#5]
Hello,

I was wondering if anyone can offer insight on a training issue that I have been running into.  I have tried to train a couple of times with the published commands and I keep getting an "aborted" message about halfway through the training:

"  failed at ihmehimmeli/tempcoding/tempcoder.cc:240: Error computing Lambert W on: -0.367879"
Aborted (core dumped)

I've tried about 3 or 4 times so far and the same error occurs at different run/epochs.  Can anyone offer any suggestions?

 As seen in the attached screenshot.  

![Screenshot 2020-11-20 150737](https://user-images.githubusercontent.com/68536805/99845126-2693fa00-2b42-11eb-8316-791f148bbe69.png)

**Comment by veluca93** [comment]
That looks like a numerical issue to me - could you try replacing this line (https://github.com/google/ihmehimmeli/blob/master/tempcoding/tempcoder.cc#L235) with `constexpr double kMinLambertArg = -1.0 / M_E + 1e-8;`?

**Comment by TheAwesomeAndy** [comment]
Thanks for the really quick response … I’m running it now and I’ll let you know if that works.   Thanks!Andrew  From: Luca VersariSent: Saturday, November 21, 2020 6:45 AMTo: google/ihmehimmeliCc: TheAwesomeAndy; AuthorSubject: Re: [google/ihmehimmeli] cc:240: Error computing Lambert W (#5) That looks like a numerical issue to me - could you try replacing this line (https://github.com/google/ihmehimmeli/blob/master/tempcoding/tempcoder.cc#L235) with constexpr double kMinLambertArg = -1.0 / M_E + 1e-8;?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by TheAwesomeAndy** [comment]
Hello, I just wanted to give an update that the proposed fix worked.  Thank you so much for the quick response
