### ISSUE TITLE
Error while Testing the network

### ISSUE THREAD

**Issue by TheAwesomeAndy** [google/ihmehimmeli#6]
Hello Again,
Sorry for the number of questions.  Would you be able to provide any insight to an error that I am getting when running the testing command:

**Error:**

"andy@andy-HP-G72-Notebook-PC:/media/andy/TOSHIBA EXT/ihmehimmeli/build$ tempcoding/tempcoding_main -model_to_test=tempcoding/networks/fast_network -problem=mnist -n_test=10000 -n_train=60000 -n_validation=0 -decay_rate=0.181769 -mnist_data_path=../data/mnist
W2020-11-28T11:40:32.120522282-05:00 /media/andy/TOSHIBA EXT/ihmehimmeli/tempcoding/spiking_problem.cc:413] Ignoring n_inputs flag for MNIST problem. Using 784 inputs.

**IHM_CHECK(file.Open(path, mode)) failed at /media/andy/TOSHIBA EXT/ihmehimmeli/tempcoding/file_passthrough_external.cc:97
Aborted (core dumped)
"**

![image](https://user-images.githubusercontent.com/68536805/100521356-2fec1a80-3171-11eb-9572-63803d10dc83.png)

Thanking you as always for any insight that you can provide,
Andrew

**Comment by veluca93** [comment]
I think the paths might be wrong - try

```
tempcoding/tempcoding_main -model_to_test=../tempcoding/networks/fast_network -problem=mnist -n_test=10000 -n_train=60000 -n_validation=0 -decay_rate=0.181769 -mnist_data_path=../data/mnist
```

**Comment by TheAwesomeAndy** [comment]
Thank you so much for the timely reply.  I’ll try that and get back to you -Andrew From: Luca VersariSent: Saturday, November 28, 2020 1:42 PMTo: google/ihmehimmeliCc: TheAwesomeAndy; AuthorSubject: Re: [google/ihmehimmeli] Error while Testing the network (#6) I think the paths might be wrong - trytempcoding/tempcoding_main -model_to_test=../tempcoding/networks/fast_network -problem=mnist -n_test=10000 -n_train=60000 -n_validation=0 -decay_rate=0.181769 -mnist_data_path=../data/mnist—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by TheAwesomeAndy** [comment]
This fix worked!  Thank you
